### ISSUE TITLE
docsearch is not working correctly

### ISSUE THREAD

**Issue by Arhell** [martrapp/astro-vtbot#114]
### Describe the Bug

when clicking on the result the modal window should close
Example https://docs.testomat.io/ not close

close https://docusaurus.io/ after search result

### What's the expected result?

Close modal

### Link to Minimal Reproducible Example

https://github.com/testomatio/docs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @Arhell, 
with out view transitions clicking the link reloads the whole page (and the modal is gone)
With view transitions, search is persistent as it sits in the app frame.

I can not test this without an APIKEY. 
But I would try to add this script to `src/components/Search.astro`
```js
<script>
  document.addEventListener("astro:before-preparation", () => {
    document.querySelector<HTMLButtonElement>(".docsearch-modal-search-cancel-btn")?.click();
  });
</script>
```

The idea here is to press the cancel button after the navigation started. That should close the modal and hopefully doesn't do anything else. Debugging third party scripts is always laborious.

**Comment by Arhell** [comment]
> Hi @Arhell, with out view transitions clicking the link reloads the whole page (and the modal is gone) With view transitions, search is persistent as it sits in the app frame.
> 
> I can not test this without an APIKEY. But I would try to add this script to `src/components/Search.astro`
> 
> ```
> <script>
>   document.addEventListener("astro:before-preparation", () => {
>     document.querySelector<HTMLButtonElement>(".docsearch-modal-search-cancel-btn")?.click();
>   });
> </script>
> ```
> 
> The idea here is to press the cancel button after the navigation started. That should close the modal and hopefully doesn't do anything else. Debugging third party scripts is always laborious.

Thanks, i try and I'll let you know about the result

**Comment by martrapp** [comment]
If you are considering to switch from `meilisearch-docsearch` to `algolia-docsearch`: there is an official starlight integration for that: https://starlight.astro.build/guides/site-search/#algolia-docsearch

**Comment by Arhell** [comment]
> algolia

Thanks, I know, we tried it. But initially there was a need to install meilisearch, since our server has a search.

I’ll write this: it wasn’t easy to do, the main thing was to correctly index the documentation repository, because everything took a lot of time.

**Comment by Arhell** [comment]
> If you are considering to switch from `meilisearch-docsearch` to `algolia-docsearch`: there is an official starlight integration for that: https://starlight.astro.build/guides/site-search/#algolia-docsearch

Thanks, I know, we tried it. But initially there was a need to install meilisearch, since our server has a search.

I’ll write this: it wasn’t easy to do, the main thing was to correctly index the documentation repository, because everything took a lot of time.

**Comment by Arhell** [comment]
Works great, thanks for the help.

**Comment by martrapp** [comment]
You are welcome, happy if it works for you!
