### ISSUE TITLE
Support for fallback

### ISSUE THREAD

**Issue by jdahdah** [martrapp/astro-vtbot#4]
First off, `astro-vtbot` is great! It allows me to keep a persistent CSS animation going across page transitions, so thank you!

One request: please add support for `<ViewTransitions fallback="animate | swap | none" />`. Astro's View Transitions allow for [setting a fallback method](https://docs.astro.build/en/guides/view-transitions/#fallback-control) in browsers that don't natively support the View Transitions API, like currently Safari and Firefox. I'm using `fallback="swap"` because I don't like the way `fallback="animate"` first hides the existing content before it shows the new content instead of a cross-fade (feels glitchy to me), so I prefer instant replacement SPA-style as a fallback. Unfortunately at the moment `astro-vtbot` seems to ignore this and instead enforces the fallback `animation` in those browsers (which I understand is the Astro default). Would be great if it could preserve the original functionality there.

**Comment by martrapp** [comment]
Hi @jdahdah! Thank you very much for the positive feedback and the interest in astro-vtbot!

I was not aware that fallback with vtbot is not working as expected. This is certainly not intentional and I would like to do something to ensure that everything works as expected.

How can I reproduce your issue? Do you have a repository or a deployment that I can take a look at?

**Comment by martrapp** [comment]
Hi @jdahdah, I was able to reproduce the issue and found the cause.
The reset to the default fallback happens in the integration part where I forgot to pass on `Astro.props`.

Will publish a patch shortly.

**Comment by jdahdah** [comment]
Hi @martrapp, apologies for not responding sooner. Thank you so much for your efforts! I'll try it out once it's released.

**Comment by martrapp** [comment]
@jdahdah no problem 😄 
First i was puzzled by your request and it took me a while to recognize what might be the problem.
Looking forward to your test: 1.4.3 is out now.

**Comment by jdahdah** [comment]
@martrapp Transitions work as expected now, thank you! (Visible [here](https://8d23a29c.dahdah-de.pages.dev/) e.g. with the language switcher, background persists). I haven't launched yet as I am getting a 404 error due to an issue with `vtbot-loading-indicator`, but will open a separate issue for that.
