### ISSUE TITLE
Starlight's sidebar visibility issues with view transitions

### ISSUE THREAD

**Issue by mearashadowfax** [martrapp/astro-vtbot#55]
### Describe the Bug

First of all, thank you for these great tools and tricks!

I am encountering a couple of issues with the view transitions implementation on my Starlight site. These issues include:

**Sidebar initially invisible**: When landing on a page with active view transitions, the sidebar is initially invisible. However, after reloading the page, the sidebar becomes visible and remains so for subsequent navigation.

**Sidebar showing up on inappropriate pages**: When navigating to certain pages, such as the docs home page, the sidebar is displayed even though it shouldn't be. Reloading the page seems to resolve this issue temporarily.

**Steps to Reproduce:**

1. Navigate to the docs site (link is in the footer).
2. Click on `Get started` button.
3. Observe that the sidebar is initially invisible.
4. Reload the page.
5. Note that the sidebar becomes visible after reloading.
6. Navigate to a page where the sidebar should not be displayed (e.g., docs home page).
7. Observe that the sidebar is still visible on the page.
8. Reload the page.
9. Note that the sidebar disappears after reloading.

### What's the expected result?

Display  a sidebar without the need to reload the page.

### Link to Minimal Reproducible Example

https://github.com/mearashadowfax/ScrewFast/pull/40

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hey @mearashadowfax! Thank you for test driving the Starlight support!
I'm sorry for the issues but try to fix them asap ;-)
