### ISSUE TITLE
Site header link is not responding on clicks

### ISSUE THREAD

**Issue by mearashadowfax** [martrapp/astro-vtbot#58]
### Describe the Bug

Hello, Martin! I'm reaching out this time regarding an issue I've encountered with the SiteTitle component, possibly related to vtbot or my setup, not sure yet. This problem arose after integrating VT into the system. 

I've implemented a custom SiteTitle component featuring two links/logos. However, upon testing, I noticed that clicking on the first link doesn't redirect to the main website. The second link/logo functions correctly, directing to the main page of docs. 

Upon inspecting the dev console, I encountered the following error: "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setAttribute')", which points to StarlightConnector.astro. 

To provide more context, here's the link to the custom component:
https://github.com/mearashadowfax/ScrewFast/blob/main/src/components/ui/starlight/SiteTitle.astro

The docs link: https://screwfast.uk/welcome-to-docs/

### What's the expected result?

When clicking on either of the two links/logos in the SiteTitle component, the user should be redirected to the corresponding URL.

### Link to Minimal Reproducible Example

https://github.com/mearashadowfax/ScrewFast/tree/add-starlight-vt

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hello @mearashadowfax! Thanks for getting in touch and opening the topic.
I'll get back to you when I have news!

**Comment by martrapp** [comment]
@mearashadowfax, your component is fine and completely unrelated to the null access error.
I will directly fix the cause of that error.

I also noticed that Starlight complains about redefined web-components `<starlight-toc>` and `<starlight-menu-button>` which is also likely a consequence of view transitions. But I was not yet able to reproduce that one.

**Comment by mearashadowfax** [comment]
Thank you for looking into the issue, @martrapp! As for the other components, I haven't noticed anything specific yet. Starlight was returning a 404 for TableOfContents.astro and MobileTableOfContents, although this existed even before the view transitions, and it seems unrelated.

**Comment by martrapp** [comment]
1.7.2 is out now! Good Luck @mearashadowfax!

**Comment by martrapp** [comment]
> As for the other components, ...

I saw on your site that starlight (or your hosting infrastructure) included some web component scripts as inline modules instead of external modules. That leads to re-registration and the errors I saw.

**Comment by mearashadowfax** [comment]
> included some web component scripts as inline modules instead of external modules. That leads to re-registration and the errors I saw.

Oh, thank you for pointing this out, I will check why.

**Comment by martrapp** [comment]
should be solved in 1.7.2
