### ISSUE TITLE
Starlight sidebar badges outlined style issue

### ISSUE THREAD

**Issue by HiDeoo** [martrapp/astro-vtbot#77]
### Describe the Bug

_Note: the issue has initially been reported in https://github.com/withastro/starlight/issues/1764_

1. Navigate to https://events-3bg.pages.dev/jotter/history-of-changes/ and notice the sidebar entry for this page containing a badge with an outlined style as expected for the current page:

<img width="263" alt="SCR-20240418-kszb" src="https://github.com/martrapp/astro-vtbot/assets/494699/a2ae1f35-cc15-4689-9335-f6d42dd24af0">

2. Navigate with a full navigation to https://events-3bg.pages.dev/jotter/ and notice the sidebar entry for the previous page ("Recent changes") with a colored badge as expected as it's not the current page:

<img width="255" alt="image" src="https://github.com/martrapp/astro-vtbot/assets/494699/ddb76655-3e6b-4225-ba48-7c4e2f07e612">

3. Navigate to the "Recent changes" page using the sidebar link and notice that the sidebar badge is not updated to an outlined style as expected for the current page:

<img width="262" alt="image" src="https://github.com/martrapp/astro-vtbot/assets/494699/e276a53c-2d20-4243-bed2-cba2252c80cf">

### What's the expected result?

The sidebar badges should be updated to an outlined style when the page is the current one (and vice versa when it's no longer the current one).

### Link to Minimal Reproducible Example

https://events-3bg.pages.dev/jotter/history-of-changes/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @HiDeoo, really great that you have posted the detailed issue! A reference to the Starlight issue would have sufficed, but of course it's much easier for me to understand this way. Thank you very much for that, I really appreciate it.

**Comment by martrapp** [comment]
Lots of options, see https://github.com/withastro/starlight/issues/1764. Looks like this issue will be closed by https://github.com/withastro/starlight/issues/1530 😄

**Comment by martrapp** [comment]
Closed after https://github.com/withastro/starlight/pull/1530 was merged
