### ISSUE TITLE
Typings stop working inside slugs

### ISSUE THREAD

**Issue by dreyfus92** [martrapp/astro-vtbot#80]
### Describe the Bug

After bootstraping a fresh Astro project using the blog template and installing the `astro-vtbot` integration the typings of the slug are set to `any` like in the following example.

## Before installing:
![image](https://github.com/martrapp/astro-vtbot/assets/85648028/18ddc6cc-11f2-4ee6-96d2-459d208bc7e9)

## After installing
![image](https://github.com/martrapp/astro-vtbot/assets/85648028/ced50b92-0364-40ba-9c6d-4176b08eda12)

I've tried reloading the window on VSCode and even restarting the `ts-server` after installing the package but for some reason the issue persists. 

### What's the expected result?

The expected result is to not have typing issues 😁

### Link to Minimal Reproducible Example

I don't a repro link

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @dreyfus92, thank you for opening this issue. I agree with the expected result and am able to reproduce it. ;-)

**Comment by martrapp** [comment]
I managed to let Astro forget about the types in `.astro/types.d.ts` that were created for the content collection.

**Comment by martrapp** [comment]
Should be fine with 1.7.11

**Comment by martrapp** [comment]
Confirmed by original user (@henriqueamaral)
